### ISSUE TITLE
[Bug]: Connot install the package on Pycharm with pip method

### ISSUE THREAD

**Issue by Carloszone** [UlionTse/translators#114]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

I tried to install this package with the Pycharm "Python package" feature but met this error
![Uploading error.PNG…]()

### APP Version

0.0.1(example)

### Python Version

3.10

### Runtime Environment

Windows 10

### Country/Region

Qatar(example)

### Relevant log output

```sh
Executed command:
list

Error occurred:
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\cli\main.py", line 57, in main_subshell
    p = generate_parser()
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 40, in generate_parser
    p = ArgumentParser(
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 117, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\base\context.py", line 422, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\plugins\__init__.py", line 3, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\plugins\hookspec.py", line 10, in <module>
    from .types import CondaSolver, CondaSubcommand, CondaVirtualPackage
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\plugins\types.py", line 6, in <module>
    from ..core.solve import Solver
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\solve.py", line 15, in <module>
    from .index import get_reduced_index, _supplement_index_with_system
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\download.py", line 12, in <module>
    from .session import CondaSession
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\adapters\s3.py", line 10, in <module>
    import boto3
  File "C:\Users\admin\anaconda3\lib\site-packages\boto3\__init__.py", line 17, in <module>
    from boto3.session import Session
  File "C:\Users\admin\anaconda3\lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\session.py", line 26, in <module>
    import botocore.client
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\utils.py", line 34, in <module>
    import botocore.httpsession
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\httpsession.py", line 41, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "C:\Users\admin\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "C:\Users\admin\anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\admin\anaconda3\lib\site-packages\OpenSSL\crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\cli\main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1424, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1127, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1167, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1178, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\exceptions.py", line 1240, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\cli\main_info.py", line 17, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 22, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\core\path_actions.py", line 28, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\download.py", line 12, in <module>
    from .session import CondaSession
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\session.py", line 11, in <module>
    from .adapters.s3 import S3Adapter
  File "C:\Users\admin\anaconda3\lib\site-packages\conda\gateways\connection\adapters\s3.py", line 10, in <module>
    import boto3
  File "C:\Users\admin\anaconda3\lib\site-packages\boto3\__init__.py", line 17, in <module>
    from boto3.session import Session
  File "C:\Users\admin\anaconda3\lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\session.py", line 26, in <module>
    import botocore.client
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\docs\shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\utils.py", line 34, in <module>
    import botocore.httpsession
  File "C:\Users\admin\anaconda3\lib\site-packages\botocore\httpsession.py", line 41, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "C:\Users\admin\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "C:\Users\admin\anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\admin\anaconda3\lib\site-packages\OpenSSL\crypto.py", line 3268, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
```

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@Carloszone Please describe the installation process in detail and re-upload the screenshot.

**Comment by Carloszone** [comment]
@UlionTse it seems a Pycharm problem because the error appearswhen I install any packages and I have solved it. Now you can close the issue. Thank you
