### ISSUE TITLE
[Bug]: Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by cm-xcju** [UlionTse/translators#123]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

ping www.baidu.com是可以成功的，但是依旧 connection refused

`Traceback (most recent call last):
  File "/home/xcju/anaconda3/envs/t17py36/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/xcju/anaconda3/envs/t17py36/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/xcju/anaconda3/envs/t17py36/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`

### APP Version

i don't know

### Python Version

>=3.6, <=3.8

### Runtime Environment

Linux Ubuntu

### Country/Region

china

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
You are right, `Baidu` doesn't work on Linux without desktop. You can read this [Debug Tips in README_detail.md](https://github.com/UlionTse/translators/blob/master/README_detail.md)
