### ISSUE TITLE
[Bug]: translators.server.TranslatorError

### ISSUE THREAD

**Issue by ganfanghong** [UlionTse/translators#131]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

translators部署后 提示 translators.server.TranslatorError

### APP Version

0.0.1(example)

### Python Version

3.9 (Default)

### Runtime Environment

Windows 10

### Country/Region

Qatar(example)

### Relevant log output

```sh
['alibaba', 'apertium', 'argos', 'baidu', 'bing', 'caiyun', 'cloudYi', 'deepl', 'elia', 'google', 'iciba', 'iflytek', 'iflyrec', 'itranslate', 'judic', 'languageWire', 'lingvanex', 'niutrans', 'mglip', 'modernMt', 'myMemory', 'papago', 'qqFanyi', 'qqTranSmart', 'reverso', 'sogou', 'sysTran', 'tilde', 'translateCom', 'translateMe', 'utibet', 'volcEngine', 'yandex', 'yeekit', 'youdao']
[2023-06-12 11:49:04,131] ERROR in app: Exception on /translation [POST]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\TranslasePy\HqdTranslate.py", line 61, in translate
    print(ts.translate_text(text,'auto',dest))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\translators\server.py", line 4902, in translate_text
    raise TranslatorError
translators.server.TranslatorError
192.168.127.1 - - [2023-06-12 11:49:04] "POST /translation HTTP/1.1" 500 136 200.668508
```

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
@UlionTse Please provide more information, also you can test it in simple environment.
