### ISSUE TITLE
[Bug]: translator caiyun: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by godv23** [UlionTse/translators#138]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

```py
import translators as ts
text = 'hello mike'
print(ts.translate_text(text,
                        translator='caiyun',
                        from_language='en',
                        to_language='zh-CN',
                        timeout=30,
                        sleep_seconds=1
                        ))
```

### APP Version

5.8.2

### Python Version

3.9 (Default)

### Runtime Environment

Windows 10

### Country/Region

Hongkong

### Relevant log output

```sh
Using region  server backend.

Traceback (most recent call last):
  File "C:\Users\13745\Desktop\code\python_project\text\SubtitleTranslate\test.py", line 29, in <module>
    print(ts.translate_text(text,
  File "C:\soft\python\lib\site-packages\translators\server.py", line 5124, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
  File "C:\soft\python\lib\site-packages\translators\server.py", line 104, in _wrapper
    return func(*args, **kwargs)
  File "C:\soft\python\lib\site-packages\translators\server.py", line 261, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
  File "C:\soft\python\lib\site-packages\translators\server.py", line 1934, in caiyun_api
    self.language_map = self.get_language_map(js_html, **debug_lang_kwargs)
  File "C:\soft\python\lib\site-packages\translators\server.py", line 215, in _wrapper
    return func(*args, **kwargs)
  File "C:\soft\python\lib\site-packages\translators\server.py", line 1862, in get_language_map
    return execjs.eval(re.compile('={auto:\\[(.*?)}').search(js_html).group()[1:])
AttributeError: 'NoneType' object has no attribute 'group'
```

### Screenshots

```Markdown
![DESCRIPTION](LINK.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UlionTse** [comment]
Copy that, Sir.

**Comment by UlionTse** [comment]
@godv23 Hello friend.
Please `pip install --upgrade translators==5.8.3`.

**Comment by UlionTse** [comment]
@godv23 You are welcome.
