### ISSUE TITLE
[Bug]: The function baidu() has been not certified yet

### ISSUE THREAD

**Issue by Leon406** [UlionTse/translators#155]
### Debug Tips

- [X] I'm sure I've read this project's Issues of README.

### What happened?

百度翻译不可用

### APP Version

5.9.0

### Python Version

3.9 (Default)

### Runtime Environment

Windows 10

### Country/Region

China

### Relevant log output

```sh
C:\Users\Leon\AppData\Roaming\Python\Python39\site-packages\grequests.py:22: MonkeyPatchWarning: Patching more than once will result in the union of all True parameters being patched
  curious_george.patch_all(thread=False, select=False)
Traceback (most recent call last):
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 296, in _wrapper
    return func(*args, **kwargs)
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 117, in _wrapper
    return func(*args, **kwargs)
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 288, in _wrapper
    return func(*args, **{**kwargs, **{'query_text': query_text}})
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 717, in baidu_api
    self.get_lang_url = re.compile(self.get_lang_url_pattern).search(host_html).group()
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\gitrepo\pyutil\CheckProxy.py", line 43, in <module>
    translated_text = ts.translate_text(
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 5469, in translate_text
    return self.translators_dict[translator](query_text=query_text, from_language=from_language, to_language=to_language, **kwargs)
  File "E:\Scoop\apps\anaconda3\current\lib\site-packages\translators\server.py", line 301, in _wrapper
    raise TranslatorError(f'{raise_tips1} {raise_tips2}')
translators.server.TranslatorError: The function baidu() has been not certified yet. Please read for details: Status of Translator on this webpage(https://github.com/UlionTse/translators#supported-translation-services).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Leon406** [comment]
百度的 get_lang_url_pattern 变了，更换下链接就可以了，正则中 ‘.’ 记得转义

`self.get_lang_url_pattern = 'https://fanyi-cdn.cdn.bcebos.com/static/cat/js/index\.(.*?)\.js'`

**Comment by UlionTse** [comment]
@Leon406 Sir, copy that!

**Comment by UlionTse** [comment]
@Benjamin8639 
1、出错的日志打印一下，复现一下问题。
2、可通过`ts.server._baidu.get_lang_url_pattern='xxxxx'`进行修改。

**Comment by Benjamin8639** [comment]
@UlionTse 
![screenshot-20241205-101128](https://github.com/user-attachments/assets/9a592f12-d74b-4f6f-8b97-8ff21d720526)
大佬，我把版本更新到了5.9.3，调用百度的翻译刚开始翻译是可以成功的，但是过了一天后，就报错了
The function baidu() has been not certified yet
