### ISSUE TITLE
Can't use Bing to translate...

### ISSUE THREAD

**Issue by FidoDidoVN** [UlionTse/translators#16]
I google, Sogou, Baidu! all is great but bing don't work! please check it!

**Comment by UlionTse** [comment]
@FidoDidoVN Show your code and error please.

**Comment by FidoDidoVN** [comment]
Thank you, This is my code:

import translators as ts

Text = "This is my Text"
google = ts.google(Text,to_language="es")
print(google)
sogou = ts.sogou(Text,to_language="es")
print(google)
bing = ts.bing(Text,to_language="es")
print(google)


and the result here:
Este es mi texto
2020-05-19 14:16:08.278 | INFO     | translators.apis:wrapper:62 - UseTimeSeconds(fn: google_api): 0.52
Este es mi texto
2020-05-19 14:16:10.471 | INFO     | translators.apis:wrapper:62 - UseTimeSeconds(fn: sogou_api): 2.19
Traceback (most recent call last):
  File "C:/Users/Fido WIn/Desktop/Fido Json Reup v1.5/test.py", line 8, in <module>
    bing = ts.bing(Text,to_language="es")
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\translators\apis.py", line 60, in wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\translators\apis.py", line 621, in bing_api
    data = r.json()
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by UlionTse** [comment]
@FidoDidoVN First, pay attention to your `print(*)`.  Second, about `google` and `bing`, you can try `if_use_cn_host=False` if you did not more frequently request .

**Comment by FidoDidoVN** [comment]
Thank you! the error tell that the code is wrong at  "line 8, in
bing = ts.bing(Text,to_language="es")" so even my print() is wrong but the code is stop at line 8. I try "if_use_cn_host=False" with the code as:
import translators as ts

Text = "This is my Text"
google = ts.google(Text,to_language="es")
print(google)
sogou = ts.sogou(Text,to_language="es")
print(sogou)
bing = ts.bing(Text,to_language="es",if_use_cn_host=False)
print(bing)

And still get the same error:
Este es mi texto
2020-05-19 15:30:52.411 | INFO     | translators.apis:wrapper:62 - UseTimeSeconds(fn: google_api): 0.67
Este es mi texto
2020-05-19 15:30:54.216 | INFO     | translators.apis:wrapper:62 - UseTimeSeconds(fn: sogou_api): 1.8
Traceback (most recent call last):
  File "C:/Users/Fido WIn/Desktop/Fido Json Reup v1.5/test.py", line 8, in <module>
    bing = ts.bing(Text,to_language="es",if_use_cn_host=False)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\translators\apis.py", line 60, in wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\translators\apis.py", line 621, in bing_api
    data = r.json()
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Fido WIn\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by UlionTse** [comment]
@FidoDidoVN The error is *No data returned by network request* . Where are you from? And `pip install translators --upgrade`, ensure the version is 4.5.4
![截屏2020-05-19 下午5 07 20](https://user-images.githubusercontent.com/14334826/82307946-aacebe80-99f3-11ea-881c-d1c6578159a9.png)

**Comment by FidoDidoVN** [comment]
I'm from Viet Nam. Yes my version is 4.5.4.

**Comment by UlionTse** [comment]
@UlionTse So you should use `if_use_cn_host=False` for `bing()`. Can you access [this website](http://bing.com/Translator) normally and translate it normally
