### ISSUE TITLE
Deepl, Bing and Baidu don't work

### ISSUE THREAD

**Issue by creke** [UlionTse/translators#17]
Would you please take a look?
Thank you!

Deepl:

```
>>> ts.deepl(s, from_language='zh', to_language='en', )                                                                        Traceback (most recent call last):                                                                                               File "<stdin>", line 1, in <module>                                                                                            File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 60, in wrapper
    r = func(*args, **kwargs)
  File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 789, in deepl_api
    r.raise_for_status()
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too many Requests for url: https://www2.deepl.com/jsonrpc
```

Bing:

```
>>> ts.bing(s, if_use_cn_host=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 60, in wrapper
    r = func(*args, **kwargs)
  File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 619, in bing_api
    data = r.json()
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Baidu:

```
>>> ts.baidu(s, use_domain='common')                                                                                           Traceback (most recent call last):                                                                                               File "<stdin>", line 1, in <module>                                                                                            File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 60, in wrapper
    r = func(*args, **kwargs)
  File "/home/qspace/data/huajiehuang/work/ugatit/translators/translators/apis.py", line 313, in baidu_api
    r.raise_for_status()
  File "/home/qspace/data/huajiehuang/softs/miniconda3/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://fanyi.baidu.com/v2transapi
```

**Comment by UlionTse** [comment]
@creke Excuse me, where are you from?  
1. Please check whether you can visit this website([https://www.deepl.com/translator](https://www.deepl.com/translator)) normally!
2. If you are in China, you should use `if_use_cn_host=True`.
3. Please check your runtime environment, some Linux environment is not supported. For example, `baidu()`.

**Comment by creke** [comment]
我是在香港的服务器，看起来deepl和baidu把一些机房的ip限制了。不知道bing是不是也是这种情况，bing我试过True和False都不行。如果您这里bing是ok的话，应该就是bing也限制了机房ip

**Comment by UlionTse** [comment]
@creke `baidu()`只要不是linux环境，应该是没有问题的。`deepl()`响应速度较慢，你可以体验一下[官网](https://www.deepl.com/translator)。`bing()`之前有个越南开发者也遇到了这个问题，但是我这边host为 [https://cn.bing.com/Translator](https://cn.bing.com/Translator)的服务是没有问题的，没办法测试其他国家或地区的具体服务情况。

**Comment by eggplants** [comment]
DeepL has stopped offering a free API. Instead, it seems to have started offering the paid DeepL Pro.
See: https://www.deepl.com/pro?cta=menu-pro
