### ISSUE TITLE
tencent不能用啦

### ISSUE THREAD

**Issue by prigioni** [UlionTse/translators#30]
Traceback (most recent call last):
  File "D:/python/trans/UlionTse_translators.py", line 15, in <module>
    print(ts.tencent(x))
  File "D:\windows\soft\anaconda3\lib\site-packages\translators\apis.py", line 65, in wrapper
    r = func(*args, **kwargs)
  File "D:\windows\soft\anaconda3\lib\site-packages\translators\apis.py", line 493, in tencent_api
    qtv = re.findall('var qtv = "(.*?)"', host_html)[0]
IndexError: list index out of range

**Comment by UlionTse** [comment]
@prigioni Which version?

**Comment by prigioni** [comment]
是的，直接下载

> @prigioni Is the newest version?

**Comment by UlionTse** [comment]
@prigioni `assert ts.__version__ == '4.7.13'`

**Comment by prigioni** [comment]
>>> import translators as ts
>>> ts.__version__
'4.7.13'
@UlionTse

**Comment by prigioni** [comment]
@UlionTse 4.7.13可以啦，但不知道怎么输出译文

**Comment by prigioni** [comment]
@UlionTse print(ts.tencent('季姬寂，集鸡，鸡即棘鸡。棘鸡饥叽，季姬及箕稷济鸡。', from_language='zh', to_language='jp'))
输出为
。

**Comment by mengguiyouziyi** [comment]
腾讯确实不能用了

**Comment by UlionTse** [comment]
Upgrade it to V4.8.0
