### ISSUE TITLE
Using Google translator, OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by demongolem** [UlionTse/translators#39]
When translating a random sentence from french to english using google, I get this rather unexpected error.  It does not appear to have anything to do with the input phrase which is being entered.

I am guessing this would be self.query_count getting too large? Perhaps a value of 1024 would do it?  Sleep seconds should be related to self.query_count in another way?

By the way, the sentence is: "Un incendie se déclare dans le séchoir à bois d’une menuiserie."

Traceback (most recent call last):
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 77, in <module>
    main()
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 74, in main
    process_links(links_file, basedata_dir)
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 54, in process_links
    result = process_link(line)
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 46, in process_link
    description_text = translate_french_to_english(content.getText())
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 16, in translate_french_to_english
    return ts.translate_html(content, translator=ts.google, to_language='en', translator_params={})
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 67, in wrapper
    r = func(*args, **kwargs)
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 1050, in translate_html
    return re.sub(pattern=pattern, repl=repl, string=html_text)
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 1049, in <lambda>
    repl = lambda x: translator(query_text=x.group(1).strip(), to_language=to_language,**translator_params) if x.group(1).strip() else ''
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 324, in google_api
    sleep_seconds = kwargs.get('sleep_seconds', 0.05 + random.random() / 2 + 1e-100 * 2 ** self.query_count)
OverflowError: int too large to convert to float

**Comment by UlionTse** [comment]
@demongolem
 
Hello, friend,
This is really a bug. Actually, if you use the `translate_html()` function, the default value of `sleep_seconds` is a very small value. But because the function input parameter form of kwargs is used (even though `sleep_seconds` has already been defined), the default value is still being calculated, and OverflowError is caused by excessive `query_count` in this calculation.

The next version I will fix this bug, and the current solution is to reset the `query_count` of the currently called translation function. For example: `ts._google.query_count = 0`

Thank you for your feedback.
