### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

### ISSUE THREAD

**Issue by demongolem-biz** [UlionTse/translators#40]
Hi, I am still doing batch french to english translation with google.  I have come across a string which is detected as French and I read it and it is French, however, I get the above error for this particular bit of text.

The input I am giving is of class 'str' and is of length 5086 (that is the content variable).  Is there a max length limit or is that fine?  Anyway for this particular str and none others I have faced, I get the error.  Let me give you the full stack trace.

Traceback (most recent call last):
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 132, in <module>
    main()
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 129, in main
    process_links(links_file, basedata_dir)
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 109, in process_links
    result = process_link(line)
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 58, in process_link
    description_text = translate_french_to_english(content.getText())
  File "/home/brick/eclipse-workspace/ARIACrawling/ProcessLinks.py", line 18, in translate_french_to_english
    returnable = ts.translate_html(content, translator=ts.google, to_language='en', translator_params={})
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 67, in wrapper
    r = func(*args, **kwargs)
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 1050, in translate_html
    return re.sub(pattern=pattern, repl=repl, string=html_text)
  File "/usr/lib64/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 1049, in <lambda>
    repl = lambda x: translator(query_text=x.group(1).strip(), to_language=to_language,**translator_params) if x.group(1).strip() else ''
  File "/home/brick/.local/lib/python3.6/site-packages/translators/apis.py", line 336, in google_api
    data = json.loads(json_data[0][2])
  File "/usr/lib64/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

**Comment by demongolem-biz** [comment]
Ok yes I see that google translate has a 5000 character limit.  Are there any strategies that can be implemented here to break down the text to get a complete translation?  In the case of translating french, I imagine that splitting the text at a sentence boundary would be good enough.

**Comment by UlionTse** [comment]
@demongolem-biz 

Hello friend,
you are right, I will improve it in the next version.
Thank you for your feedback
