### ISSUE TITLE
google挂逼了

### ISSUE THREAD

**Issue by LiHang941** [UlionTse/translators#45]
I love you
{'en': ['en', 'auto'], 'auto': ['en', 'auto']}
Traceback (most recent call last):
  File "translation.py", line 96, in <module>
    parse()
  File "translation.py", line 64, in parse
    print(ts.google('我爱你', from_language=from_language, to_language="en"))
  File "/usr/local/lib/python3.8/dist-packages/translators/apis.py", line 367, in google_api
    from_language, to_language = self.check_language(from_language, to_language, self.language_map, output_zh=self.output_zh)
  File "/usr/local/lib/python3.8/dist-packages/translators/apis.py", line 106, in check_language
    raise TranslatorError('Unsupported from_language[{}] in {}.'.format(from_language,sorted(language_map.keys())))
translators.apis.TranslatorError: Unsupported from_language[zh-CN] in ['auto', 'en'].

**Comment by LiHang941** [comment]
![image](https://user-images.githubusercontent.com/29689440/125777367-76352796-fee9-4421-acae-d1ed4fcd90b1.png)

**Comment by UlionTse** [comment]
Which version?

**Comment by LiHang941** [comment]
> Which version?

请问4.8.0修复了吗，获取language_map失败了

**Comment by UlionTse** [comment]
👌
