### ISSUE TITLE
Yandex error

### ISSUE THREAD

**Issue by MelonHell** [UlionTse/translators#63]
ts.yandex(text, from_language="ru", to_language="en")

```
Using Russia server backend.
Ignoring exception in on_message
Traceback (most recent call last):
  File "D:\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "E:\Desktop\CP77_Ru_Modding_Discord_Bot\main.py", line 48, in on_message
    await translate(channel["en"], message, "ru", "en")
  File "E:\Desktop\CP77_Ru_Modding_Discord_Bot\main.py", line 24, in translate
    new_text = ts.yandex(message.content, from_language=lang_from, to_language=lang_to)
  File "C:\Program Files\Python310\lib\site-packages\translators\apis.py", line 1311, in yandex_api
    self.sid = self.get_sid(host_html)
  File "C:\Program Files\Python310\lib\site-packages\translators\apis.py", line 1260, in get_sid
    sid_find = re.compile("SID: '(.*?)',").findall(host_html)[0]
IndexError: list index out of range
```

**Comment by UlionTse** [comment]
@MelonHell Please provide more information, such as runtime environment, package version, and simple test performance.
My test performance:
<img width="369" alt="截屏2022-03-23 上午10 50 08" src="https://user-images.githubusercontent.com/14334826/159614270-7f1d047f-a33f-439f-b95d-9c427bacb5ae.png">
